### ISSUE TITLE
Anystyle CSL parsing error - CSLRefType.IV

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-backend#101]
While importing dataset 11
-----

```
org.col.admin.task.importer.NormalizationFailedException: Failed to read ACEF files
	at org.col.admin.task.importer.acef.AcefInserter.batchInsert(AcefInserter.java:66)
	at org.col.admin.task.importer.NeoInserter.insertAll(NeoInserter.java:84)
	at org.col.admin.task.importer.Normalizer.insertData(Normalizer.java:596)
	at org.col.admin.task.importer.Normalizer.run(Normalizer.java:68)
	at org.col.admin.task.importer.Normalizer.run(Normalizer.java:55)
	at org.col.admin.task.importer.ImportJob.importDataset(ImportJob.java:111)
	at org.col.admin.task.importer.ImportJob.call(ImportJob.java:71)
	at org.col.admin.task.importer.ImportManager.runImport(ImportManager.java:110)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: com.fasterxml.jackson.databind.JsonMappingException: No enum constant org.col.api.vocab.CSLRefType.IV (through reference chain: java.util.ArrayList[0]->org.col.api.model.CslData["type"])
	at org.col.csl.AnystyleParserWrapper.parse(AnystyleParserWrapper.java:56)
	at org.col.admin.task.importer.reference.ReferenceFactory.parse(ReferenceFactory.java:109)
	at org.col.admin.task.importer.reference.ReferenceFactory.fromACEF(ReferenceFactory.java:67)
	at org.col.admin.task.importer.acef.AcefInserter.lambda$insertReferences$3(AcefInserter.java:137)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at org.col.admin.task.importer.acef.AcefInserter.insertReferences(AcefInserter.java:136)
	at org.col.admin.task.importer.acef.AcefInserter.batchInsert(AcefInserter.java:62)
	... 13 common frames omitted
Caused by: com.fasterxml.jackson.databind.JsonMappingException: No enum constant org.col.api.vocab.CSLRefType.IV (through reference chain: java.util.ArrayList[0]->org.col.api.model.CslData["type"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:391)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:351)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1689)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:289)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:285)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4001)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3065)
	at org.col.csl.AnystyleParserWrapper.parse(AnystyleParserWrapper.java:49)
	... 21 common frames omitted
Caused by: java.lang.IllegalArgumentException: No enum constant org.col.api.vocab.CSLRefType.IV
	at java.lang.Enum.valueOf(Enum.java:238)
	at org.col.api.vocab.CSLRefType.valueOf(CSLRefType.java:7)
	at org.col.api.jackson.CSLRefTypeSerde$Deserializer.deserialize(CSLRefTypeSerde.java:44)
	at org.col.api.jackson.CSLRefTypeSerde$Deserializer.deserialize(CSLRefTypeSerde.java:39)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:287)
	... 28 common frames omitted
```

**Comment by mdoering** [comment]
also seeing this in dataset 130:
`JsonMappingException: No enum constant org.col.api.vocab.CSLRefType.`

**Comment by mdoering** [comment]
dataset 8: 
`IllegalArgumentException: No enum constant org.col.api.vocab.CSLRefType.1929`

**Comment by mdoering** [comment]
Looks like most (all?) datasets fail to import because of that deserialisation error

**Comment by mdoering** [comment]
related to #102
