### ISSUE TITLE
PersistenceException: Reference Key (id, dataset_key)=(http://biostor.org/reference/98760, 1018) already exists

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-backend#112]
Questions:
 - how is Reference.id populated? 
 - do we do a lookup/test for the same id?
 - exception handling in duplicate id cases (also for other entities)?

```
org.apache.ibatis.exceptions.PersistenceException: 
### Error updating database.  Cause: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "reference_id_dataset_key_idx"
  Detail: Key (id, dataset_key)=(http://biostor.org/reference/98760, 1018) already exists.
### The error may involve org.col.db.mapper.ReferenceMapper.create-Inline
### The error occurred while setting parameters
### SQL: INSERT INTO reference (           id,         dataset_key,         verbatim_key,         csl,         serial_key,         year,         issues       )         VALUES (           ?,         ?,         ?,         ?::jsonb,         ?,         ?,         ?::int[]       )
### Cause: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "reference_id_dataset_key_idx"
  Detail: Key (id, dataset_key)=(http://biostor.org/reference/98760, 1018) already exists.
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:200)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:185)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:57)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:59)
	at com.sun.proxy.$Proxy120.create(Unknown Source)
	at org.col.admin.task.importer.PgImport.insertReferences(PgImport.java:150)
	at org.col.admin.task.importer.PgImport.run(PgImport.java:66)
	at org.col.admin.task.importer.ImportJob.importDataset(ImportJob.java:115)
	at org.col.admin.task.importer.ImportJob.call(ImportJob.java:71)
	at org.col.admin.task.importer.ImportManager.runImport(ImportManager.java:114)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "reference_id_dataset_key_idx"
  Detail: Key (id, dataset_key)=(http://biostor.org/reference/98760, 1018) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2477)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2190)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:300)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:169)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:158)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:46)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:74)
	at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:50)
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:198)
	... 15 common frames omitted
```

**Comment by mdoering** [comment]
this is fixed by solving #108
