### ISSUE TITLE
Dataset 2006 import failed. 

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-backend#123]
```
org.apache.ibatis.exceptions.PersistenceException: 
### Error updating database.  Cause: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "reference_id_dataset_key_idx"
  Detail: Key (id, dataset_key)=(10.1007/bf00012180, 2006) already exists.
### The error may involve org.col.db.mapper.ReferenceMapper.create-Inline
### The error occurred while setting parameters
### SQL: INSERT INTO reference (           id,         dataset_key,         verbatim_key,         csl,         citation,         year       )         VALUES (           ?,         ?,         ?,         ?::jsonb,         ?,         ?       )
### Cause: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "reference_id_dataset_key_idx"
  Detail: Key (id, dataset_key)=(10.1007/bf00012180, 2006) already exists.
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:200)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:185)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:57)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:59)
	at com.sun.proxy.$Proxy122.create(Unknown Source)
	at org.col.admin.importer.PgImport.insertReferences(PgImport.java:161)
	at org.col.admin.importer.PgImport.call(PgImport.java:75)
	at org.col.admin.importer.ImportJob.importDataset(ImportJob.java:143)
	at org.col.admin.importer.ImportJob.run(ImportJob.java:84)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "reference_id_dataset_key_idx"
  Detail: Key (id, dataset_key)=(10.1007/bf00012180, 2006) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2477)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2190)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:300)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:169)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:158)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:46)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:74)
	at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:50)
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:198)
	... 12 common frames omitted
```

**Comment by mdoering** [comment]
dataset 2006 went through fine this time
