### ISSUE TITLE
org.col.common.io.DownloadException for unit test zip archives

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-backend#235]
When trying to import a unit test archive from the data-unit-tests repo, the downloader is returning a 404 error, even though the [zip archive is there](https://github.com/Sp2000/data-unit-tests/raw/master/C1.zip). Here's the [kibana logs](https://logs.gbif.org/goto/d3d2167e46695831b0a2e1427c9a626d).

```
environment:
    col
dataset:
    2046
level:
    ERROR
message:
    Dataset 2046 import failed. Download of https://github.com/Sp2000/data-unit-tests/raw/master/C1.zip failed. org.col.common.io.DownloadException: Download of https://github.com/Sp2000/data-unit-tests/raw/master/C1.zip failed. http 404 Not Found for URL https://github.com/Sp2000/data-unit-tests/raw/master/C1.zip. Log to db
@timestamp:
    8th January 2019, 12:55:41.543
task:
    ImportJob
thread_name:
    dataset-importer-17
level_value:
    40,000
@version:
    1
host:
    130.225.43.113
logger_name:
    org.col.admin.importer.ImportJob
stack_trace:
    org.col.common.io.DownloadException: Download of https://github.com/Sp2000/data-unit-tests/raw/master/C1.zip failed. org.col.common.io.DownloadException: Download of https://github.com/Sp2000/data-unit-tests/raw/master/C1.zip failed. http 404 Not Found for URL https://github.com/Sp2000/data-unit-tests/raw/master/C1.zip at org.col.common.io.DownloadUtil.downloadIfModifiedSince(DownloadUtil.java:141) at org.col.common.io.DownloadUtil.downloadIfModified(DownloadUtil.java:76) at org.col.admin.importer.ImportJob.importDataset(ImportJob.java:155) at org.col.admin.importer.ImportJob.run(ImportJob.java:107) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748) Caused by: org.col.common.io.DownloadException: Download of https://github.com/Sp2000/data-unit-tests/raw/master/C1.zip failed. http 404 Not Found for URL https://github.com/Sp2000/data-unit-tests/raw/master/C1.zip at org.col.common.io.DownloadUtil.downloadIfModifiedSince(DownloadUtil.java:137) ... 8 common frames omitted 
class:
    admin-server
_id:
    AWgu0gHyl3jPXJpw_Gpu
_type:
    logs
_index:
    col-admin-server-2019.01.08
_score:
    - 
```

**Comment by mdoering** [comment]
curl gives me a 404 too:
```
$ curl --head https://github.com/Sp2000/data-unit-tests/raw/master/C1.zip
HTTP/1.1 404 Not Found
Server: GitHub.com
Date: Tue, 08 Jan 2019 20:51:59 GMT
Content-Type: text/html; charset=utf-8
Status: 404 Not Found
```

It is a little tricky with private github repos.
If you check your browser you will see the URL returns a 302 redirect to `Location: https://raw.githubusercontent.com/Sp2000/data-unit-tests/master/C1.zip?token=SOMETOKEN`. The redirect only works from the browser (if you are logged in I assume).

To overcome this I have configured our downloader to append a configurable token.
But its not being applied to the githubusercontent.com domain so far, I will add that.

The correct URL would then be `https://raw.githubusercontent.com/Sp2000/data-unit-tests/master/C1.zip`

**Comment by mdoering** [comment]
The simplest solution for now is to make that repo public, there is nothing to hide!

**Comment by mdoering** [comment]
needs a jenkins build and redeploy until you can use it, Ill do that tomorrow

**Comment by gdower** [comment]
Thanks! We need permission from the GSDs before we can open the repos.

**Comment by mdoering** [comment]
You need permissions for tiny test datasets with a few records? Anyway, jenkins is nearly done I might be able to deploy in 5 minutes
