### ISSUE TITLE
Import sector rematching error

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-backend#342]
Rematching existing sectors after an import can bring the entire import down when the source taxon is now shared by several sectors, ie. breaks unique constraint.

This needs to be caught and somehoe handled, e.g. sectors merged???

```
Dataset 1141 import failed. 
### Error updating database.  Cause: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "sector_dataset_key_subject_id_key"
  Detail: Key (dataset_key, subject_id)=(1141, x7Ap1) already exists.
### The error may involve org.col.db.mapper.SectorMapper.update-Inline
### The error occurred while setting parameters
### SQL: UPDATE sector     SET (      dataset_key,     subject_id,     subject_name,     subject_authorship,     subject_rank,     target_id,     target_name,     target_authorship,     target_rank,     mode,     note,     modified,     modified_by    ) = (      ?,     ?,     ?,     ?,     ?::rank,     ?,     ?,     ?,     ?::rank,     ?,     ?,     now(),     ?    )     WHERE key = ?
### Cause: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "sector_dataset_key_subject_id_key"
  Detail: Key (dataset_key, subject_id)=(1141, x7Ap1) already exists.. Log to db

org.apache.ibatis.exceptions.PersistenceException: 
### Error updating database.  Cause: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "sector_dataset_key_subject_id_key"
  Detail: Key (dataset_key, subject_id)=(1141, x7Ap1) already exists.
### The error may involve org.col.db.mapper.SectorMapper.update-Inline
### The error occurred while setting parameters
### SQL: UPDATE sector     SET (      dataset_key,     subject_id,     subject_name,     subject_authorship,     subject_rank,     target_id,     target_name,     target_authorship,     target_rank,     mode,     note,     modified,     modified_by    ) = (      ?,     ?,     ?,     ?,     ?::rank,     ?,     ?,     ?,     ?::rank,     ?,     ?,     now(),     ?    )     WHERE key = ?
### Cause: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "sector_dataset_key_subject_id_key"
  Detail: Key (dataset_key, subject_id)=(1141, x7Ap1) already exists.
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:200)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:63)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:59)
	at com.sun.proxy.$Proxy149.update(Unknown Source)
	at org.col.dao.DecisionRematcher.matchSector(DecisionRematcher.java:97)
	at org.col.dao.DecisionRematcher.matchDatasetNoLogs(DecisionRematcher.java:179)
	at org.col.dao.DecisionRematcher.matchDataset(DecisionRematcher.java:171)
	at org.col.importer.ImportJob.importDataset(ImportJob.java:204)
	at org.col.importer.ImportJob.run(ImportJob.java:113)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "sector_dataset_key_subject_id_key"
  Detail: Key (dataset_key, subject_id)=(1141, x7Ap1) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:132)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:46)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:74)
	at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:50)
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:198)
	... 13 common frames omitted
```

**Comment by mdoering** [comment]
rematching makes sure the source id is unique and assigns a null id in case of duplicates for manual resolution later on
