### ISSUE TITLE
PUT on dataset/<datasetKey>/name/<nameId> gives 500

### ISSUE THREAD

**Issue by thomasstjerne** [Sp2000/colplus-backend#354]
In order to implement https://github.com/Sp2000/colplus-frontend/issues/183

**Comment by mdoering** [comment]
got a log entry?

**Comment by thomasstjerne** [comment]
There was an error processing your request. It has been logged (ID ba5ef037f57f3a5c)

**Comment by mdoering** [comment]
... we also need to think about guarding too drastic spelling changes as ids need to remain stable

**Comment by mdoering** [comment]
```
org.apache.ibatis.exceptions.PersistenceException: 
### Error updating database.  Cause: org.postgresql.util.PSQLException: ERROR: syntax error at or near "("
  Position: 15
### The error may involve org.col.db.mapper.NameMapper.update-Inline
### The error occurred while setting parameters
### SQL: UPDATE name_3 (          id,         dataset_key,         sector_key,         verbatim_key,         name_index_id,         homotypic_name_id,         scientific_name,         scientific_name_normalized,         authorship,         authorship_normalized,         rank,         uninomial,         genus,         infrageneric_epithet,         specific_epithet,         infraspecific_epithet,         cultivar_epithet,         strain,         candidatus,         notho,         basionym_authors,         basionym_ex_authors,         basionym_year,         combination_authors,         combination_ex_authors,         combination_year,         sanctioning_author,         published_in_id,         published_in_page,         code,         nom_status,         origin,         type,         webpage,         fossil,         remarks,         created_by,         modified_by      , created, modified)         VALUES (          ?,         ?,         ?,         ?,         ?,         ?,         ?,         ?,         ?,         ?,         ?::rank,         ?,         ?,         ?,         ?,         ?,         ?,         ?,         ?,         ?,         ?,         ?,         ?,         ?,         ?,         ?,         ?,         ?,         ?,         ?,         ?,         ?,         ?,         ?,         ?,         ?,         ?,         ?      , now(), now())
### Cause: org.postgresql.util.PSQLException: ERROR: syntax error at or near "("
  Position: 15
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:200)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:63)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:59)
	at com.sun.proxy.$Proxy97.update(Unknown Source)
	at org.col.dao.DatasetEntityDao.update(DatasetEntityDao.java:74)
	at org.col.resources.DatasetEntityResource.update(DatasetEntityResource.java:64)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Comment by thomasstjerne** [comment]
Is at desirable too have a PUT in the assembly tree at all?

**Comment by mdoering** [comment]
- do we want to allow to move a taxon, i.e. update its parentID? I think yes
 - do we want to allow name changes? only if its error correction, but thats gonna be hard to determine. Maybe its better to create a new one, move children and delete the old one?
