### ISSUE TITLE
PUT on /dataset/3/taxon/<ID> gives 500

### ISSUE THREAD

**Issue by thomasstjerne** [Sp2000/colplus-backend#366]
When drag-dropping a taxon to another parent, the UI updates the parentId and tries to PUT:

https://api-dev.col.plus/dataset/3/taxon/1d266f3f-3df0-4e24-9785-09fb914c457f
```
{"code":500,"message":"There was an error processing your request. It has been logged (ID 32ac9fb86097ae40)."}
```

**Comment by mdoering** [comment]
```
java.lang.NullPointerException: null
	at org.col.dao.TaxonDao.mergeMapCounts(TaxonDao.java:343)
	at org.col.dao.TaxonDao.parentChanged(TaxonDao.java:337)
	at org.col.dao.TaxonDao.updateAfter(TaxonDao.java:323)
	at org.col.dao.TaxonDao.updateAfter(TaxonDao.java:22)
	at org.col.dao.DatasetEntityDao.update(DatasetEntityDao.java:75)
	at org.col.resources.DatasetEntityResource.update(DatasetEntityResource.java:64)
```
