### ISSUE TITLE
Cyrillic characters are causing the importer to crash

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-backend#389]
A reference in GSD1201 had a the Cyrillic small letter о, which was causing the importer to crash:

Contribuci**о**nes al conocimiento de la flora del Gondwana Superior en la Argentina. XXXIII \"Ginkgoales\" de los Estratos de Potrerillos en la Precordillera de Mendoza.

This is one of the worst kinds of data bugs because о and o look nearly identical. This bug occurs somewhat frequently in data and is likely introduced by OCR readers. Ideally the importer needs to be able to handle those characters without crashing but report them as an issue. Here's a [temporary test repo](https://github.com/gdower/data-import-tester/archive/master.zip) that can be used to test this bug. If the о on [line 2 of references](https://github.com/gdower/data-import-tester/blob/master/acef/References.tsv#L2) is replaced with o, the importer runs fine.

Here's the [crash log](https://logs.gbif.org/app/kibana#/context/AWGthDPVf8lu3pmEwvFE/logs/AWso8d_ArbHgAYk4sphW?_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!t,index:AWBa0XR-f8lu3pmE7ete,key:environment,negate:!f,type:phrase,value:col-prod),query:(match:(environment:(query:col-prod,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!t,index:AWGthDPVf8lu3pmEwvFE,key:level,negate:!t,type:phrase,value:DEBUG),query:(match:(level:(query:DEBUG,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!t,index:AWGthDPVf8lu3pmEwvFE,key:level,negate:!t,type:phrase,value:INFO),query:(match:(level:(query:INFO,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!t,index:AWGthDPVf8lu3pmEwvFE,key:dataset,negate:!f,type:phrase,value:'2063'),query:(match:(dataset:(query:'2063',type:phrase))))),predecessorCount:5,sort:!('@timestamp',desc),successorCount:5)&_g=(refreshInterval:(display:On,pause:!f,value:0),time:(from:now-7d,mode:quick,to:now))):
```
org.col.importer.NormalizationFailedException: Failed to read ACEF files
	at org.col.importer.acef.AcefInserter.batchInsert(AcefInserter.java:101)
	at org.col.importer.NeoInserter.insertAll(NeoInserter.java:74)
	at org.col.importer.Normalizer.insertData(Normalizer.java:806)
	at org.col.importer.Normalizer.call(Normalizer.java:77)
	at org.col.importer.ImportJob.importDataset(ImportJob.java:184)
	at org.col.importer.ImportJob.run(ImportJob.java:113)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Key.hashCode() changed after serialization, make sure to use correct Key Serializer
	at org.mapdb.HTreeMap.put(HTreeMap.kt:315)
	at org.col.importer.neo.NeoDb.create(NeoDb.java:525)
	at org.col.importer.NeoInserter.lambda$insertEntities$2(NeoInserter.java:125)
	at org.col.importer.NeoInserter.lambda$processVerbatim$1(NeoInserter.java:100)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at org.col.importer.NeoInserter.processVerbatim(NeoInserter.java:98)
	at org.col.importer.NeoInserter.insertEntities(NeoInserter.java:119)
	at org.col.importer.acef.AcefInserter.batchInsert(AcefInserter.java:62)
	... 10 common frames omitted
```

**Comment by mdoering** [comment]
Thats interesting and the same error as #391.
I am quite surprised it should be related to char encodings, but I did into this

**Comment by mdoering** [comment]
Ha, it indeed is. The map is configured to expect an ASCII key only - because we normalise the reference citation and thereby also fold it to ASCII. But that does not seem to work for cyrillic. I guess I better change the map to allow any strings
