### ISSUE TITLE
NeoDb.create(Reference) throws IllegalArgumentException

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-backend#391]
This appears to be one of the main causes of failed ACEF imports. It also seems like a code bug
> Dataset 2071 import failed. Failed to read ACEF files. Log to db
--
t stack_trace |   | org.col.importer.NormalizationFailedException: Failed to read ACEF files 	at org.col.importer.acef.AcefInserter.batchInsert(AcefInserter.java:101) 	at org.col.importer.NeoInserter.insertAll(NeoInserter.java:74) 	at org.col.importer.Normalizer.insertData(Normalizer.java:806) 	at org.col.importer.Normalizer.call(Normalizer.java:77) 	at org.col.importer.ImportJob.importDataset(ImportJob.java:184) 	at org.col.importer.ImportJob.run(ImportJob.java:113) 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) 	at java.lang.Thread.run(Thread.java:748) Caused by: java.lang.IllegalArgumentException: Key.hashCode() changed after serialization, make sure to use correct Key Serializer 	at org.mapdb.HTreeMap.put(HTreeMap.kt:315) 	at org.col.importer.neo.NeoDb.create(NeoDb.java:525) 	at org.col.importer.NeoInserter.lambda$insertEntities$2(NeoInserter.java:125) 	at org.col.importer.NeoInserter.lambda$processVerbatim$1(NeoInserter.java:100) 	at java.util.Iterator.forEachRemaining(Iterator.java:116) 	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) 	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) 	at org.col.importer.NeoInserter.processVerbatim(NeoInserter.java:98) 	at org.col.importer.NeoInserter.insertEntities(NeoInserter.java:119) 	at org.col.importer.acef.AcefInserter.batchInsert(AcefInserter.java:62)

**Comment by mdoering** [comment]
duplicate of #389
