### ISSUE TITLE
Name search service fails on dev server with 501 error

### ISSUE THREAD

**Issue by ayco-at-naturalis** [Sp2000/colplus-backend#40]
Name searches on dev searches fail with a 501 error and no message. No entry in the log file appears as far as I am aware. Name search runs on my local machine.

Example:
http://api.col.plus/name/search/?q=larus

**Comment by mdoering** [comment]
https://logs.gbif.org/app/kibana#/doc/AWGthDPVf8lu3pmEwvFE/col-ws-server-2018.02.22/logs?id=AWG-O0d-f8lu3pmEA3Mb&_g=(refreshInterval:(display:On,pause:!f,value:0),time:(from:now-7d,mode:quick,to:now))
```
stack_trace |   | org.apache.commons.lang3.NotImplementedException:  	at org.col.api.model.NameSearchResult.<init>(NameSearchResult.java:17) 	at org.col.db.mapper.temp.NameSearchResultTemp.toNameSearchResult(NameSearchResultTemp.java:16) 	at org.col.db.dao.NameDao.lambda$search$0(NameDao.java:122) 	at java.util.ArrayList.forEach(ArrayList.java:1257) 	at org.col.db.dao.NameDao.search(NameDao.java:122) 	at org.col.resources.NameResource.search(NameResource.java:40) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	at java.lang.reflect.Method.invoke(Method.java:498) 	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) 	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205) 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) 	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326) 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) 	at org.glassfish.jersey.internal.Errors.process(Errors.java:315) 	at org.glassfish.jersey.internal.Errors.process(Errors.java:297) 	at org.glassfish.jersey.internal.Errors.process(Errors.java:267) 	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) 	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) 	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) 	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473) 	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427) 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388) 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341) 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228) 	at io.dropwizard.jetty.NonblockingServletHolder.handle(NonblockingServletHolder.java:49) 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650) 	at io.dropwizard.servlets.ThreadNameFilter.doFilter(ThreadNameFilter.java:34) 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637) 	at io.dropwizard.jersey.filter.AllowedMethodsFilter.handle(AllowedMethodsFilter.java:45) 	at io.dropwizard.jersey.filter.AllowedMethodsFilter.doFilter(AllowedMethodsFilter.java:39) 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637) 	at org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:308) 	at org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:262) 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637) 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533) 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188) 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253) 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168) 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473) 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166) 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155) 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) 	at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:241) 	at io.dropwizard.jetty.RoutingHandler.handle(RoutingHandler.java:52) 	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:527) 	at io.dropwizard.jetty.BiDiGzipHandler.handle(BiDiGzipHandler.java:68) 	at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:56) 	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:169) 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) 	at org.eclipse.jetty.server.Server.handle(Server.java:530) 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:347) 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:256) 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279) 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102) 	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124) 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247) 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140) 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131) 	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:382) 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708) 	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626) 	at java.lang.Thread.run(Thread.java:748)
```
