### ISSUE TITLE
GET /assembly/3 gives 500

### ISSUE THREAD

**Issue by thomasstjerne** [Sp2000/colplus-backend#402]
https://api-dev.col.plus/assembly/3

**Comment by thomasstjerne** [comment]
I think this happened after attempts to sync these sectors: https://api-dev.col.plus/assembly/3/sync?limit=25&offset=0

**Comment by mdoering** [comment]
```
java.lang.IllegalStateException: Non running or waiting sync with state FAILED found in queue for sector 17
	at org.col.assembly.AssemblyState.<init>(AssemblyState.java:31)
	at org.col.assembly.AssemblyCoordinator.getState(AssemblyCoordinator.java:92)
	at org.col.resources.AssemblyResource.state(AssemblyResource.java:46)
```
related to importer queue refactoring I would think
