### ISSUE TITLE
500 error on delete subtree in assembly modify tree

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-backend#418]
I get a 500 error when trying to delete a subtree in the assembly modify tree tool:

![image](https://user-images.githubusercontent.com/8573609/60833698-7019ba00-a184-11e9-8ba0-41cc30e02a13.png)

Here's the API call:
```
https://api-dev.col.plus/dataset/3/tree/3550af76-a014-47d4-870d-3b6e82095cad
Host: api-dev.col.plus
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Referer: http://localhost:3000/
Authorization: Bearer [redacted]
Origin: http://localhost:3000
DNT: 1
Connection: keep-alive
DELETE: HTTP/1.1 500 Internal Server Error
Date: Mon, 08 Jul 2019 18:16:11 GMT
Server: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: OPTIONS, HEAD, GET, POST, PUT, DELETE
Access-Control-Allow-Headers: Authorization, Content-Type, Accept-Language, X-Requested-With
Content-Length: 0
Connection: close

```

Here's the [Kibana stack trace](https://logs.gbif.org/app/kibana#/context/AWGthDPVf8lu3pmEwvFE/logs/AWvSzpwnrbHgAYk4RMU-?_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!t,index:AWBa0XR-f8lu3pmE7ete,key:environment,negate:!f,type:phrase,value:col),query:(match:(environment:(query:col,type:phrase))))),predecessorCount:5,sort:!('@timestamp',desc),successorCount:5)&_g=(refreshInterval:(display:On,pause:!f,value:0),time:(from:now-15m,mode:quick,to:now))):
```
java.lang.NullPointerException: null
	at org.col.dw.jersey.exception.PersistenceExceptionMapper.toResponse(PersistenceExceptionMapper.java:37)
	at org.col.dw.jersey.exception.PersistenceExceptionMapper.toResponse(PersistenceExceptionMapper.java:19)
	at org.glassfish.jersey.server.ServerRuntime$Responder.mapException(ServerRuntime.java:601)
	at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:476)
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:334)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
	at io.dropwizard.jetty.NonblockingServletHolder.handle(NonblockingServletHolder.java:49)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1623)
	at io.dropwizard.servlets.ThreadNameFilter.doFilter(ThreadNameFilter.java:35)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at io.dropwizard.jersey.filter.AllowedMethodsFilter.handle(AllowedMethodsFilter.java:45)
	at io.dropwizard.jersey.filter.AllowedMethodsFilter.doFilter(AllowedMethodsFilter.java:39)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:239)
	at io.dropwizard.jetty.RoutingHandler.handle(RoutingHandler.java:52)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:703)
	at io.dropwizard.jetty.BiDiGzipHandler.handle(BiDiGzipHandler.java:67)
	at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:56)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:174)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:505)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:698)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:804)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by mdoering** [comment]
I just checked the code and all included sectors are also removed.
Maybe users should be warned

**Comment by mdoering** [comment]
getting a new error now:
`{"code":400,"message":"\n### Error updating database.  Cause: org.postgresql.util.PSQLException: ERROR: update or delete on table \"name_usage_3\" violates foreign key constraint \"name_usage_3_parent_id_fk\" on table \"name_usage_3\"\n  Detail: Key (id)=(d72ec1b3-5aa6-4790-bab8-6a1358240a7d) is still referenced from table \"name_usage_3\".\n### The error may exist in org/col/db/mapper/TaxonMapper.xml\n### The error may involve org.col.db.mapper.TaxonMapper.delete-Inline\n### The error occurred while setting parameters\n### SQL: DELETE FROM name_usage_3         WHERE id = ? AND NOT is_synonym\n### Cause: org.postgresql.util.PSQLException: ERROR: update or delete on table \"name_usage_3\" violates foreign key constraint \"name_usage_3_parent_id_fk\" on table \"name_usage_3\"\n  Detail: Key (id)=(d72ec1b3-5aa6-4790-bab8-6a1358240a7d) is still referenced from table \"name_usage_3\"."}`
