### ISSUE TITLE
CoLDP NameRel table with NULL as relatedNameID seems to crash the importer

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-backend#433]
Currently trying to import the CoLDP NameRel table with NULL as relatedNameID seems to [crash the importer](https://logs.gbif.org/app/kibana#/discover?_g=(refreshInterval:(display:On,pause:!f,value:0),time:(from:now-7d,mode:quick,to:now))&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:AWBa0XR-f8lu3pmE7ete,key:environment,negate:!f,type:phrase,value:col-prod),query:(match:(environment:(query:col-prod,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:AWGthDPVf8lu3pmEwvFE,key:level,negate:!t,type:phrase,value:DEBUG),query:(match:(level:(query:DEBUG,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:AWGthDPVf8lu3pmEwvFE,key:level,negate:!t,type:phrase,value:INFO),query:(match:(level:(query:INFO,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:AWGthDPVf8lu3pmEwvFE,key:dataset,negate:!f,type:phrase,value:'1140'),query:(match:(dataset:(query:'1140',type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:AWGthDPVf8lu3pmEwvFE,key:attempt,negate:!f,type:phrase,value:'1'),query:(match:(attempt:(query:'30',type:phrase))))),index:AWGthDPVf8lu3pmEwvFE,interval:auto,query:(match_all:()),sort:!('@timestamp',desc))). Setting the ID to the non-existent ID 'unknown' results in nomen superfluous relationship not being set. If I set the nameID and relatedNameID equal, the name is designated as nomen superfluous but that might not be the best approach for handling incomplete data.

see #432

**Comment by mdoering** [comment]
```
org.col.importer.ImportJob


Dataset 1140 import failed. Failed to read ColDP files. Log to db


org.col.importer.NormalizationFailedException: Failed to read ColDP files 	at org.col.importer.coldp.ColdpInserter.batchInsert(ColdpInserter.java:118) 	at org.col.importer.NeoInserter.insertAll(NeoInserter.java:74) 	at org.col.importer.Normalizer.insertData(Normalizer.java:803) 	at org.col.importer.Normalizer.call(Normalizer.java:77) 	at org.col.importer.ImportJob.importDataset(ImportJob.java:191) 	at org.col.importer.ImportJob.run(ImportJob.java:116) 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) 	at java.lang.Thread.run(Thread.java:748) Caused by: java.lang.NullPointerException: null 	at org.mapdb.HTreeMap.get(HTreeMap.kt:596) 	at java.util.concurrent.ConcurrentMap.getOrDefault(ConcurrentMap.java:80) 	at org.col.importer.neo.NeoCRUDStore.nodeByID(NeoCRUDStore.java:67) 	at org.col.importer.NeoInserter.lambda$insertNameRelations$4(NeoInserter.java:175) 	at org.col.importer.NeoInserter.lambda$processVerbatim$1(NeoInserter.java:100) 	at java.util.Iterator.forEachRemaining(Iterator.java:116) 	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) 	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) 	at org.col.importer.NeoInserter.processVerbatim(NeoInserter.java:98) 	at org.col.importer.NeoInserter.insertNameRelations(NeoInserter.java:171) 	at org.col.importer.coldp.ColdpInserter.batchInsert(ColdpInserter.java:77) 	... 10 common frames omitted


```
