### ISSUE TITLE
No enum constant org.col.api.vocab.Country.KOSOVO

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-backend#447]
@mdoering, do you have Kosovo in the gazetteer used to normalize countries? The importer might be crashing on Kosovo in the distribution for World Plants. Would I just add Kosovo to [this file](https://github.com/Sp2000/colplus-backend/blob/e83f7c3ae5367c382274e45c3c38329673ac037f/colplus-api/src/main/java/org/col/api/vocab/Country.java)?

Probably the importer shouldn't crash when it encounters an unknown country, but should flag it as an UNKNOWN_VOCAB issue so that we can improve the vocab?

Here's the [stacktrace](https://logs.gbif.org/app/kibana#/context/AWyLa4mQHCKcR6PFXu4X/logs/AWy5i8TwHCKcR6PFbzNs?_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!t,index:AWyLa4mQHCKcR6PFXu4X,key:level,negate:!f,params:!(WARN,ERROR),type:phrases,value:'WARN,+ERROR'),query:(bool:(minimum_should_match:1,should:!((match_phrase:(level:WARN)),(match_phrase:(level:ERROR))))))))):

```
org.col.importer.NormalizationFailedException: Failed to read ACEF files
	at org.col.importer.acef.AcefInserter.batchInsert(AcefInserter.java:101)
	at org.col.importer.NeoInserter.insertAll(NeoInserter.java:74)
	at org.col.importer.Normalizer.insertData(Normalizer.java:803)
	at org.col.importer.Normalizer.call(Normalizer.java:77)
	at org.col.importer.ImportJob.importDataset(ImportJob.java:191)
	at org.col.importer.ImportJob.run(ImportJob.java:116)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: No enum constant org.col.api.vocab.Country.KOSOVO
	at java.lang.Enum.valueOf(Enum.java:238)
	at org.col.api.util.VocabularyUtils.convertEnum(VocabularyUtils.java:157)
	at org.col.parser.CountryParser.convertFromGbif(CountryParser.java:55)
	at org.col.parser.CountryParser.convertFromGbif(CountryParser.java:12)
	at org.col.parser.GbifParserBased.parse(GbifParserBased.java:30)
	at org.col.parser.CountryParser.parse(CountryParser.java:23)
	at org.col.parser.AreaParser.normalizeAndValidate(AreaParser.java:93)
	at org.col.parser.AreaParser.parse(AreaParser.java:65)
	at org.col.parser.SafeParser.<init>(SafeParser.java:23)
	at org.col.parser.SafeParser.parse(SafeParser.java:17)
	at org.col.importer.InterpreterBase.createDistributions(InterpreterBase.java:131)
	at org.col.importer.InterpreterBase.interpretDistribution(InterpreterBase.java:97)
	at org.col.importer.acef.AcefInterpreter.interpretDistribution(AcefInterpreter.java:79)
	at org.col.importer.NeoInserter.lambda$insertTaxonEntities$3(NeoInserter.java:138)
	at org.col.importer.NeoInserter.lambda$processVerbatim$1(NeoInserter.java:100)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647)
	at org.col.importer.NeoInserter.processVerbatim(NeoInserter.java:98)
	at org.col.importer.NeoInserter.insertTaxonEntities(NeoInserter.java:136)
	at org.col.importer.acef.AcefInserter.batchInsert(AcefInserter.java:88)
	... 10 common frames omitted
```

Frontend version: 6058086 August 21, 2019 7:04 AM
Backend version: a1681bf August 21, 2019 1:33 PM

**Comment by mdoering** [comment]
It should clearly not fail, a surprise. Should be fixed now
