### ISSUE TITLE
Broken CCW Tipuloidea sector

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-backend#448]
@mdoering, I'm [investigating the broken sectors](https://github.com/Sp2000/colplus-repo/issues/45). The [CCW Tipuloidea sector is in the classification tree](https://www.col.plus/assembly?assemblyTaxonKey=7cd47d13-29b8-4f29-bf0e-aa17a3030ac6), but the sector doesn't show in the source: 

![image](https://user-images.githubusercontent.com/8573609/63545062-27c41a80-c4ec-11e9-82cc-cb5b3094b20b.png)

It might be related (or might be the #437 search bug), but Diptera doesn't show up in the left Assembly search.

Also, the data wasn't synced so is [missing in CoL+](http://workbench.catalogueoflife.org/col_plus/browse/tree/id/18be1f670535b378cd404859862a9a2f).

Here's the [stacktrace](https://logs.gbif.org/app/kibana#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-5y,mode:quick,to:now))&_a=(columns:!(_source),index:AWyLa4mQHCKcR6PFXu4X,interval:auto,query:(query_string:(analyze_wildcard:!t,query:Tipuloidea)),sort:!('@timestamp',desc))):

```
org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: java.lang.NullPointerException
### The error may exist in org/col/db/mapper/NameUsageMapper.xml
### The error may involve org.col.db.mapper.NameUsageMapper.processTree
### The error occurred while handling results
### SQL: WITH RECURSIVE x AS(         SELECT           u.is_synonym,                             u.id AS id,         u.dataset_key AS dataset_key,         u.sector_key AS sector_key,         u.verbatim_key AS verbatim_key,         u.status AS status,         u.origin AS origin,         u.parent_id AS parent_id,         u.according_to AS according_to,         u.reference_ids AS reference_ids,         u.remarks AS remarks,         u.created AS created,         u.created_by AS created_by,         u.modified AS modified,         u.modified_by AS modified_by      ,         u.according_to_date AS according_to_date,         u.fossil AS fossil,         u.recent AS recent,         u.lifezones AS lifezones,         u.webpage AS webpage      ,                             n.id AS n_id,         n.scientific_name AS n_scientific_name,         n.authorship AS n_authorship,         n.rank AS n_rank,         n.uninomial AS n_uninomial,         n.genus AS n_genus,         n.infrageneric_epithet AS n_infrageneric_epithet,         n.specific_epithet AS n_specific_epithet,         n.infraspecific_epithet AS n_infraspecific_epithet,         n.cultivar_epithet AS n_cultivar_epithet,         n.appended_phrase AS n_appended_phrase,         n.candidatus AS n_candidatus,         n.notho AS n_notho,         n.basionym_authors AS n_basionym_authors,         n.basionym_ex_authors AS n_basionym_ex_authors,         n.basionym_year AS n_basionym_year,         n.combination_authors AS n_combination_authors,         n.combination_ex_authors AS n_combination_ex_authors,         n.combination_year AS n_combination_year,         n.sanctioning_author AS n_sanctioning_author,         n.code AS n_code      ,         n.dataset_key AS n_dataset_key,         n.sector_key AS n_sector_key,         n.verbatim_key AS n_verbatim_key,         n.name_index_id AS n_name_index_id,         n.homotypic_name_id AS n_homotypic_name_id,         n.published_in_id AS n_published_in_id,         n.published_in_page AS n_published_in_page,         n.nom_status AS n_nom_status,         n.origin AS n_origin,         n.type AS n_type,         n.webpage AS n_webpage,         n.fossil AS n_fossil,         n.remarks AS n_remarks,         n.created AS n_created,         n.created_by AS n_created_by,         n.modified AS n_modified,         n.modified_by AS n_modified_by      ,                             a.id AS a_id,         a.dataset_key AS a_dataset_key,         a.sector_key AS a_sector_key,         a.verbatim_key AS a_verbatim_key,         a.status AS a_status,         a.origin AS a_origin,         a.parent_id AS a_parent_id,         a.according_to AS a_according_to,         a.reference_ids AS a_reference_ids,         a.remarks AS a_remarks,         a.created AS a_created,         a.created_by AS a_created_by,         a.modified AS a_modified,         a.modified_by AS a_modified_by      ,         a.according_to_date AS a_according_to_date,         a.fossil AS a_fossil,         a.recent AS a_recent,         a.lifezones AS a_lifezones,         a.webpage AS a_webpage      ,                             an.id AS a_n_id,         an.scientific_name AS a_n_scientific_name,         an.authorship AS a_n_authorship,         an.rank AS a_n_rank,         an.uninomial AS a_n_uninomial,         an.genus AS a_n_genus,         an.infrageneric_epithet AS a_n_infrageneric_epithet,         an.specific_epithet AS a_n_specific_epithet,         an.infraspecific_epithet AS a_n_infraspecific_epithet,         an.cultivar_epithet AS a_n_cultivar_epithet,         an.appended_phrase AS a_n_appended_phrase,         an.candidatus AS a_n_candidatus,         an.notho AS a_n_notho,         an.basionym_authors AS a_n_basionym_authors,         an.basionym_ex_authors AS a_n_basionym_ex_authors,         an.basionym_year AS a_n_basionym_year,         an.combination_authors AS a_n_combination_authors,         an.combination_ex_authors AS a_n_combination_ex_authors,         an.combination_year AS a_n_combination_year,         an.sanctioning_author AS a_n_sanctioning_author,         an.code AS a_n_code      ,         an.dataset_key AS a_n_dataset_key,         an.sector_key AS a_n_sector_key,         an.verbatim_key AS a_n_verbatim_key,         an.name_index_id AS a_n_name_index_id,         an.homotypic_name_id AS a_n_homotypic_name_id,         an.published_in_id AS a_n_published_in_id,         an.published_in_page AS a_n_published_in_page,         an.nom_status AS a_n_nom_status,         an.origin AS a_n_origin,         an.type AS a_n_type,         an.webpage AS a_n_webpage,         an.fossil AS a_n_fossil,         an.remarks AS a_n_remarks,         an.created AS a_n_created,         an.created_by AS a_n_created_by,         an.modified AS a_n_modified,         an.modified_by AS a_n_modified_by                               FROM           name_usage_1005 u             JOIN name_1005 n ON u.name_id=n.id             LEFT JOIN name_usage_1005 a ON u.parent_id=a.id AND u.is_synonym             LEFT JOIN name_1005 an ON a.name_id=an.id               WHERE                           u.id = ?                       AND NOT u.is_synonym                    UNION          SELECT           u.is_synonym,                             u.id AS id,         u.dataset_key AS dataset_key,         u.sector_key AS sector_key,         u.verbatim_key AS verbatim_key,         u.status AS status,         u.origin AS origin,         u.parent_id AS parent_id,         u.according_to AS according_to,         u.reference_ids AS reference_ids,         u.remarks AS remarks,         u.created AS created,         u.created_by AS created_by,         u.modified AS modified,         u.modified_by AS modified_by      ,         u.according_to_date AS according_to_date,         u.fossil AS fossil,         u.recent AS recent,         u.lifezones AS lifezones,         u.webpage AS webpage      ,                             n.id AS n_id,         n.scientific_name AS n_scientific_name,         n.authorship AS n_authorship,         n.rank AS n_rank,         n.uninomial AS n_uninomial,         n.genus AS n_genus,         n.infrageneric_epithet AS n_infrageneric_epithet,         n.specific_epithet AS n_specific_epithet,         n.infraspecific_epithet AS n_infraspecific_epithet,         n.cultivar_epithet AS n_cultivar_epithet,         n.appended_phrase AS n_appended_phrase,         n.candidatus AS n_candidatus,         n.notho AS n_notho,         n.basionym_authors AS n_basionym_authors,         n.basionym_ex_authors AS n_basionym_ex_authors,         n.basionym_year AS n_basionym_year,         n.combination_authors AS n_combination_authors,         n.combination_ex_authors AS n_combination_ex_authors,         n.combination_year AS n_combination_year,         n.sanctioning_author AS n_sanctioning_author,         n.code AS n_code      ,         n.dataset_key AS n_dataset_key,         n.sector_key AS n_sector_key,         n.verbatim_key AS n_verbatim_key,         n.name_index_id AS n_name_index_id,         n.homotypic_name_id AS n_homotypic_name_id,         n.published_in_id AS n_published_in_id,         n.published_in_page AS n_published_in_page,         n.nom_status AS n_nom_status,         n.origin AS n_origin,         n.type AS n_type,         n.webpage AS n_webpage,         n.fossil AS n_fossil,         n.remarks AS n_remarks,         n.created AS n_created,         n.created_by AS n_created_by,         n.modified AS n_modified,         n.modified_by AS n_modified_by      ,                             a.id AS a_id,         a.dataset_key AS a_dataset_key,         a.sector_key AS a_sector_key,         a.verbatim_key AS a_verbatim_key,         a.status AS a_status,         a.origin AS a_origin,         a.parent_id AS a_parent_id,         a.according_to AS a_according_to,         a.reference_ids AS a_reference_ids,         a.remarks AS a_remarks,         a.created AS a_created,         a.created_by AS a_created_by,         a.modified AS a_modified,         a.modified_by AS a_modified_by      ,         a.according_to_date AS a_according_to_date,         a.fossil AS a_fossil,         a.recent AS a_recent,         a.lifezones AS a_lifezones,         a.webpage AS a_webpage      ,                             an.id AS a_n_id,         an.scientific_name AS a_n_scientific_name,         an.authorship AS a_n_authorship,         an.rank AS a_n_rank,         an.uninomial AS a_n_uninomial,         an.genus AS a_n_genus,         an.infrageneric_epithet AS a_n_infrageneric_epithet,         an.specific_epithet AS a_n_specific_epithet,         an.infraspecific_epithet AS a_n_infraspecific_epithet,         an.cultivar_epithet AS a_n_cultivar_epithet,         an.appended_phrase AS a_n_appended_phrase,         an.candidatus AS a_n_candidatus,         an.notho AS a_n_notho,         an.basionym_authors AS a_n_basionym_authors,         an.basionym_ex_authors AS a_n_basionym_ex_authors,         an.basionym_year AS a_n_basionym_year,         an.combination_authors AS a_n_combination_authors,         an.combination_ex_authors AS a_n_combination_ex_authors,         an.combination_year AS a_n_combination_year,         an.sanctioning_author AS a_n_sanctioning_author,         an.code AS a_n_code      ,         an.dataset_key AS a_n_dataset_key,         an.sector_key AS a_n_sector_key,         an.verbatim_key AS a_n_verbatim_key,         an.name_index_id AS a_n_name_index_id,         an.homotypic_name_id AS a_n_homotypic_name_id,         an.published_in_id AS a_n_published_in_id,         an.published_in_page AS a_n_published_in_page,         an.nom_status AS a_n_nom_status,         an.origin AS a_n_origin,         an.type AS a_n_type,         an.webpage AS a_n_webpage,         an.fossil AS a_n_fossil,         an.remarks AS a_n_remarks,         an.created AS a_n_created,         an.created_by AS a_n_created_by,         an.modified AS a_n_modified,         an.modified_by AS a_n_modified_by                               FROM           name_usage_1005 u             JOIN name_1005 n ON u.name_id=n.id             LEFT JOIN name_usage_1005 a ON u.parent_id=a.id AND u.is_synonym             LEFT JOIN name_1005 an ON a.name_id=an.id               JOIN x ON x.id = u.parent_id                     )         SELECT * FROM x
### Cause: java.lang.NullPointerException
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.select(DefaultSqlSession.java:171)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.select(DefaultSqlSession.java:157)
	at org.apache.ibatis.binding.MapperMethod.executeWithResultHandler(MapperMethod.java:136)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:77)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:57)
	at com.sun.proxy.$Proxy153.processTree(Unknown Source)
	at org.col.assembly.SectorSync.processTree(SectorSync.java:188)
	at org.col.assembly.SectorSync.sync(SectorSync.java:90)
	at org.col.assembly.SectorSync.doWork(SectorSync.java:43)
	at org.col.assembly.SectorRunnable.run(SectorRunnable.java:96)
	at org.col.assembly.SectorSync.run(SectorSync.java:29)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: null
	at org.col.assembly.TreeCopyHandler.handleResult(TreeCopyHandler.java:218)
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.callResultHandler(DefaultResultSetHandler.java:370)
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.storeObject(DefaultResultSetHandler.java:363)
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleRowValuesForNestedResultMap(DefaultResultSetHandler.java:866)
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleRowValues(DefaultResultSetHandler.java:326)
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleResultSet(DefaultResultSetHandler.java:304)
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleResultSets(DefaultResultSetHandler.java:194)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:65)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:79)
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:63)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:324)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:136)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.select(DefaultSqlSession.java:169)
	... 15 common frames omitted
```

This would've been based on yesterday's deployment which I think was:

Frontend version: 6058086 August 21, 2019 11:22 AM
Backend version: e206678 August 19, 2019 8:57 AM

**Comment by gdower** [comment]
Actually doing a rematch fixed the sector, although oddly the frontend threw an error:

```
Rematch failed
Missing ID: target and subject
```

**Comment by gdower** [comment]
The same exact thing was reproducible with Reptilia, including the rematch error when rematch actually worked.

**Comment by mdoering** [comment]
@thomasstjerne we need to figure out what the rematch really does, weird behavior.
WHenever a sector is not showing on the left (target) or right (subject) tree it means the ids in the sector do not match up. After wiping the environment all sectors now should match. Please check this, if not then we need to fix the init scripts. 

When a sector is broken after an import that is strange and needs more investigation. I'll try to reproduce this, but no time until late tomorrow

**Comment by gdower** [comment]
@mdoering, I'm wondering if it's the sector mapping export from AG+ that's incorrect. I think rematch actually worked for most of the broken sectors. I could see the rematched sectors in the assembly tree and source pane, and I was able to sync the data after rematching. I guess we'll see what happens after I run conversion though.

**Comment by mdoering** [comment]
closing as its synced now in prod
