### ISSUE TITLE
Buffer underflow while importing on dev

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-backend#458]
I was trying to reproduce a nested sectors bug on dev that we had on prod with GSD63, and got a buffer underflow error when trying to import GSD63. Here's the Kibana [stacktrace](https://logs.gbif.org/app/kibana#/context/AWyLa2lBHCKcR6PFXu26/logs/AWzi8CZfHCKcR6PFVw81?_a=(columns:!(_source),filters:!(),predecessorCount:5,sort:!('@timestamp',desc),successorCount:5)&_g=(refreshInterval:(display:On,pause:!f,value:0),time:(from:now-7d,mode:quick,to:now))):

```
com.esotericsoftware.kryo.KryoException: Buffer underflow.
Serialization trace:
infraspecificEpithetQualifier (org.col.api.model.Name)
	at com.esotericsoftware.kryo.io.Input.require(Input.java:199)
	at com.esotericsoftware.kryo.io.Input.readUtf8_slow(Input.java:560)
	at com.esotericsoftware.kryo.io.Input.readUtf8(Input.java:553)
	at com.esotericsoftware.kryo.io.Input.readString(Input.java:483)
	at com.esotericsoftware.kryo.serializers.DefaultSerializers$StringSerializer.read(DefaultSerializers.java:199)
	at com.esotericsoftware.kryo.serializers.DefaultSerializers$StringSerializer.read(DefaultSerializers.java:188)
	at com.esotericsoftware.kryo.Kryo.readObjectOrNull(Kryo.java:782)
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:132)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:543)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:813)
	at com.esotericsoftware.kryo.serializers.CollectionSerializer.read(CollectionSerializer.java:134)
	at com.esotericsoftware.kryo.serializers.CollectionSerializer.read(CollectionSerializer.java:40)
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:709)
	at org.col.common.kryo.map.MapDbObjectSerializer.deserialize(MapDbObjectSerializer.java:56)
	at org.mapdb.StoreDirectAbstract.deserialize(StoreDirectAbstract.kt:229)
	at org.mapdb.StoreDirect.get(StoreDirect.kt:546)
	at org.mapdb.HTreeMap.valueUnwrap(HTreeMap.kt:1200)
	at org.mapdb.HTreeMap.getprotected(HTreeMap.kt:644)
	at org.mapdb.HTreeMap.get(HTreeMap.kt:603)
	at org.col.matching.NameIndexMapDB.match(NameIndexMapDB.java:149)
	at org.col.importer.Normalizer.lambda$matchAndCount$2(Normalizer.java:269)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
	at org.col.importer.Normalizer.matchAndCount(Normalizer.java:268)
	at org.col.importer.Normalizer.call(Normalizer.java:91)
	at org.col.importer.ImportJob.importDataset(ImportJob.java:191)
	at org.col.importer.ImportJob.run(ImportJob.java:116)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

Frontend version: 3b50e4e August 29, 2019 6:39 AM
Backend version: 53ee7ee August 30, 2019 7:03 AM

**Comment by gdower** [comment]
Actually all imports are failing so this is probably just a temporary issue with dev.

**Comment by mdoering** [comment]
Ah, I think I know why. I have changed the ranks vocabulary to add 2 virus values (realm and subrealm) - I should have wiped dev. Ill do that now and try to import 1063
