### ISSUE TITLE
Failed import with java.io.IOException: listener timeout after waiting for [30000] ms

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-backend#467]
World Plants failed to import on the first try yesterday because of an elastic search timeout. Here's the [stacktrace](https://logs.gbif.org/app/kibana#/context/AWyLa4mQHCKcR6PFXu4X/logs/AW0YEyW7HCKcR6PFJYaQ?_a=(columns:!(_source),filters:!(),predecessorCount:5,sort:!('@timestamp',desc),successorCount:5)&_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-24h,mode:quick,to:now))):

```
org.col.es.EsException: java.io.IOException: listener timeout after waiting for [30000] ms
	at org.col.es.NameUsageIndexServiceEs.indexDataset(NameUsageIndexServiceEs.java:76)
	at org.col.importer.ImportJob.importDataset(ImportJob.java:209)
	at org.col.importer.ImportJob.run(ImportJob.java:116)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: listener timeout after waiting for [30000] ms
	at org.elasticsearch.client.RestClient$SyncResponseListener.get(RestClient.java:905)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:229)
	at org.col.es.EsUtil.deleteByQuery(EsUtil.java:161)
	at org.col.es.EsUtil.deleteDataset(EsUtil.java:108)
	at org.col.es.NameUsageIndexServiceEs.createOrEmptyIndex(NameUsageIndexServiceEs.java:198)
	at org.col.es.NameUsageIndexServiceEs.indexDataset(NameUsageIndexServiceEs.java:60)
	... 7 common frames omitted
```

Frontend version: 5e066ea September 10, 2019 8:46 AM
Backend version: 530045e September 9, 2019 11:45 AM

**Comment by gdower** [comment]
I can't reproduce it so far, so it might be safe to close this and I can re-open it if I hit the same issue.

**Comment by gdower** [comment]
I hit the same elastic search timeout bug again for World Plants. Here's the [Kibana hits for this bug](https://logs.gbif.org/app/kibana#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-5y,mode:quick,to:now))&_a=(columns:!(_source),index:AWyLa4mQHCKcR6PFXu4X,interval:auto,query:(query_string:(analyze_wildcard:!t,query:java.io.IOException)),sort:!('@timestamp',desc))).

(Same versions as above.)

**Comment by mdoering** [comment]
I hit the same error last night importing [Index Fungorum](https://www.col.plus/dataset/2034/metrics)

**Comment by mdoering** [comment]
@ayco-at-naturalis The weird thing is that EsClientFactory defines 120000ms for the socket timeout, but we see the error after the default 30000ms. Sounds like the wrong client is being used.

**Comment by ayco-at-naturalis** [comment]
OK, will look into it today

**Comment by mdoering** [comment]
I made the settings configurable. I cant see any reason why we should still get the wrong default values
