### ISSUE TITLE
Disable SSL validation for proxy datasets?

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-backend#520]
We might need a way to disable SSL validation for proxy datasets in the yaml file, or maybe we should consider disabling SSL validation in general for proxy datasets? The connection probably really doesn't need to be SSL encrypted.

I think I was able to fix the issue by changing the domain in this case, although[ github raw caches content and I'm waiting for that to expire](https://stackoverflow.com/questions/46551413/github-not-update-raw-after-commit). I wouldn't be surprised if we hit this issue again but with expired certificates instead.

Here's the [stacktrace](https://logs.gbif.org/app/kibana#/discover?_g=(refreshInterval:(display:On,pause:!f,value:0),time:(from:now-7d,mode:quick,to:now))&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:AWyLa2lBHCKcR6PFXu26,key:environment,negate:!f,type:phrase,value:col-dev),query:(match:(environment:(query:col-dev,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:AWyLa2lBHCKcR6PFXu26,key:level,negate:!t,type:phrase,value:DEBUG),query:(match:(level:(query:DEBUG,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:AWyLa2lBHCKcR6PFXu26,key:level,negate:!t,type:phrase,value:INFO),query:(match:(level:(query:INFO,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:AWyLa2lBHCKcR6PFXu26,key:dataset,negate:!f,type:phrase,value:'2052'),query:(match:(dataset:(query:'2052',type:phrase))))),index:AWyLa2lBHCKcR6PFXu26,interval:auto,query:(match_all:()),sort:!('@timestamp',desc))):

```
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1946)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:316)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:310)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1639)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:223)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1037)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:965)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1064)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:404)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:364)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:374)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at org.col.importer.yaml.DistributedArchiveService.download(DistributedArchiveService.java:71)
	at org.col.importer.yaml.DistributedArchiveService.download(DistributedArchiveService.java:47)
	at org.col.importer.ImportJob.importDataset(ImportJob.java:172)
	at org.col.importer.ImportJob.run(ImportJob.java:122)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:397)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:302)
	at sun.security.validator.Validator.validate(Validator.java:262)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:330)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:237)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:132)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1621)
	... 28 common frames omitted
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:392)
	... 34 common frames omitted
```

Related #518

**Comment by mdoering** [comment]
that is for a raw github URL `https://raw.githubusercontent.com/Sp2000/colplus-repo/master/registry/1054.yaml` ? Rather strange that github has this issue.

**Comment by gdower** [comment]
Actually it turns out that:

http://rameau.snv.jussieu.fr/4d4life/psyllist/AcceptedSpecies.csv

Redirects to: 

http://www.hemiptera-databases.org/4d4life/psyllist/AcceptedSpecies.csv

Which forces SSL with a bad or weak certificate:

```
wget http://rameau.snv.jussieu.fr/4d4life/psyllist/AcceptedSpecies.csv
--2019-10-20 04:11:29--  http://rameau.snv.jussieu.fr/4d4life/psyllist/AcceptedSpecies.csv
Resolving rameau.snv.jussieu.fr (rameau.snv.jussieu.fr)... 134.157.190.222
Connecting to rameau.snv.jussieu.fr (rameau.snv.jussieu.fr)|134.157.190.222|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://www.hemiptera-databases.org/4d4life/psyllist/AcceptedSpecies.csv [following]
--2019-10-20 04:11:29--  https://www.hemiptera-databases.org/4d4life/psyllist/AcceptedSpecies.csv
Resolving www.hemiptera-databases.org (www.hemiptera-databases.org)... 134.157.190.222
Connecting to www.hemiptera-databases.org (www.hemiptera-databases.org)|134.157.190.222|:443... connected.
ERROR: cannot verify www.hemiptera-databases.org's certificate, issued by ‘CN=Encryption Everywhere DV TLS CA - G1,OU=www.digicert.com,O=DigiCert Inc,C=US’:
  Unable to locally verify the issuer's authority.
```

**Comment by mdoering** [comment]
yes, I just dont get why `http://www.hemiptera-databases.org` does a SSL handshake.
Anyways, Ill try to losen things. Digging into the Dropwizard configs to change it

**Comment by mdoering** [comment]
https://github.com/Sp2000/colplus-backend/commit/432067730fe8ab2d19935a5484472a5f9885958e
