### ISSUE TITLE
/reference returns 500

### ISSUE THREAD

**Issue by MortenHofft** [Sp2000/colplus-backend#54]
http://api.col.plus/reference should this return something else than 500. bad request perhaps?

**Comment by mdoering** [comment]
it should be a paging resultset: https://sp2000.github.io/colplus/api/api.html#resource-22

**Comment by mdoering** [comment]
NPE:

```
java.lang.NullPointerException: null
	at org.col.resources.ReferenceResource.list(ReferenceResource.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```
