### ISSUE TITLE
Imports are failing due to nameIndexMatchType

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-backend#560]
Imports are failing in commit 4bb657a with the error:

```
Invalid ordinal for enum "org.col.api.vocab.MatchType": 21 Serialization trace: nameIndexMatchType (org.col.api.model.Name)
```

![image](https://user-images.githubusercontent.com/8573609/68966277-51b37300-07a3-11ea-888f-8af3659d4ad1.png)

Here's the [stacktrace](https://logs.gbif.org/app/kibana#/context/AWyLa4mQHCKcR6PFXu4X/logs/AW5wCjrQHCKcR6PFLwHs?_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!t,index:AWyLa4mQHCKcR6PFXu4X,key:environment,negate:!f,type:phrase,value:col-prod),query:(match:(environment:(query:col-prod,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!t,index:AWyLa4mQHCKcR6PFXu4X,key:level,negate:!t,type:phrase,value:DEBUG),query:(match:(level:(query:DEBUG,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!t,index:AWyLa4mQHCKcR6PFXu4X,key:level,negate:!t,type:phrase,value:INFO),query:(match:(level:(query:INFO,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!t,index:AWyLa4mQHCKcR6PFXu4X,key:dataset,negate:!f,type:phrase,value:'1027'),query:(match:(dataset:(query:'1027',type:phrase))))),predecessorCount:5,sort:!('@timestamp',desc),successorCount:5)&_g=(refreshInterval:(display:On,pause:!f,value:0),time:(from:now-7d,mode:quick,to:now))):

```JAVA
com.esotericsoftware.kryo.KryoException: Invalid ordinal for enum "org.col.api.vocab.MatchType": 21
Serialization trace:
nameIndexMatchType (org.col.api.model.Name)
	at com.esotericsoftware.kryo.serializers.DefaultSerializers$EnumSerializer.read(DefaultSerializers.java:418)
	at com.esotericsoftware.kryo.serializers.DefaultSerializers$EnumSerializer.read(DefaultSerializers.java:387)
	at com.esotericsoftware.kryo.Kryo.readObjectOrNull(Kryo.java:782)
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:132)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:543)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:813)
	at com.esotericsoftware.kryo.serializers.CollectionSerializer.read(CollectionSerializer.java:134)
	at com.esotericsoftware.kryo.serializers.CollectionSerializer.read(CollectionSerializer.java:40)
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:709)
	at org.col.common.kryo.map.MapDbObjectSerializer.deserialize(MapDbObjectSerializer.java:56)
	at org.mapdb.StoreDirectAbstract.deserialize(StoreDirectAbstract.kt:229)
	at org.mapdb.StoreDirect.get(StoreDirect.kt:546)
	at org.mapdb.HTreeMap.valueUnwrap(HTreeMap.kt:1200)
	at org.mapdb.HTreeMap.getprotected(HTreeMap.kt:644)
	at org.mapdb.HTreeMap.get(HTreeMap.kt:603)
	at org.col.matching.NameIndexMapDB.match(NameIndexMapDB.java:149)
	at org.col.importer.Normalizer.lambda$matchAndCount$2(Normalizer.java:267)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
	at org.col.importer.Normalizer.matchAndCount(Normalizer.java:266)
	at org.col.importer.Normalizer.call(Normalizer.java:89)
	at org.col.importer.ImportJob.importDataset(ImportJob.java:206)
	at org.col.importer.ImportJob.run(ImportJob.java:122)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Frontend version: 4d9dc98 November 12, 2019 7:30 AM
Backend version: 4bb657a November 15, 2019 1:42 AM

**Comment by gdower** [comment]
@mdoering, the issue seems to be specific to stable prod, because import is working on dev, unless the bug is caused by the frontend:

Frontend version: 6e85fd0 November 14, 2019 5:29 AM
Backend version: 4bb657a November 15, 2019 1:42 AM
