### ISSUE TITLE
Imports failing on dev: NoClassDefFoundError

### ISSUE THREAD

**Issue by thomasstjerne** [Sp2000/colplus-backend#573]
NoClassDefFoundError: org/bouncycastle/jce/provider/BouncyCastleProvider

```
java.lang.NoClassDefFoundError: org/bouncycastle/jce/provider/BouncyCastleProvider
	at org.neo4j.kernel.configuration.ssl.SslPolicyLoader.<init>(SslPolicyLoader.java:76)
	at org.neo4j.kernel.configuration.ssl.SslPolicyLoader.create(SslPolicyLoader.java:96)
	at org.neo4j.kernel.impl.factory.CommunityEditionModule.<init>(CommunityEditionModule.java:103)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:158)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:125)
	at org.neo4j.graphdb.factory.GraphDatabaseFactory.newDatabase(GraphDatabaseFactory.java:137)
	at org.neo4j.graphdb.factory.GraphDatabaseFactory.newEmbeddedDatabase(GraphDatabaseFactory.java:130)
	at org.neo4j.graphdb.factory.GraphDatabaseFactory$1.newDatabase(GraphDatabaseFactory.java:107)
	at org.neo4j.graphdb.factory.GraphDatabaseBuilder.newGraphDatabase(GraphDatabaseBuilder.java:199)
	at life.catalogue.importer.neo.NeoDb.openNeo(NeoDb.java:170)
	at life.catalogue.importer.neo.NeoDb.<init>(NeoDb.java:131)
	at life.catalogue.importer.neo.NeoDbFactory.create(NeoDbFactory.java:46)
	at life.catalogue.importer.neo.NeoDbFactory.persistentDb(NeoDbFactory.java:30)
	at life.catalogue.importer.neo.NeoDbFactory.create(NeoDbFactory.java:64)
	at life.catalogue.importer.ImportJob.importDataset(ImportJob.java:204)
	at life.catalogue.importer.ImportJob.run(ImportJob.java:122)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: org.bouncycastle.jce.provider.BouncyCastleProvider
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)

```

**Comment by mdoering** [comment]
Ouch, neo4j 3.4 is not fully java 11 compatible it seems

**Comment by mdoering** [comment]
```
[INFO] +- org.neo4j:neo4j-kernel:jar:3.4.17:compile
[INFO] |  \- org.neo4j:neo4j-ssl:jar:3.4.17:compile
[INFO] |     \- org.bouncycastle:bcpkix-jdk15on:jar:1.60:compile
[INFO] |        \- org.bouncycastle:bcprov-jdk15on:jar:1.64:test
```

**Comment by mdoering** [comment]
might also be OpenJDK on CentOS related.
The SSL provider chosen by neo is configurable: 
`dbms.netty.ssl.provider is one of `JDK`, `OPENSSL`, `OPENSSL_REFCNT``
