### ISSUE TITLE
Vernacular name sex sync error

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-backend#590]
When trying to sync Basidiomycetes on dev, sync failed due to vn.sex missing. Prior to that, I had created the kingdom Fungi and phylum Basidiomycetes and then tried to do replace Basidiomycetes when dragging Basidiomycetes onto Basidiomycetes. It attached the Basidiomycetes class children directly to the kingdom, which was not what I expected it would do, so I deleted that sector and then dragged Basidiomycetes onto Fungi, and tried to sync resulting in the error below.

Here's the [logs from the sector sync](https://logs.gbif.org/app/kibana#/discover?_g=(refreshInterval:(display:On,pause:!f,value:0),time:(from:now-4h,mode:quick,to:now))&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:AWyLa2lBHCKcR6PFXu26,key:sector,negate:!f,type:phrase,value:'33739'),query:(match:(sector:(query:33739,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:AWyLa2lBHCKcR6PFXu26,key:attempt,negate:!f,type:phrase,value:'2'),query:(match:(attempt:(query:2,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:AWyLa2lBHCKcR6PFXu26,key:environment,negate:!f,type:phrase,value:col-dev),query:(match:(environment:(query:col-dev,type:phrase))))),index:AWyLa2lBHCKcR6PFXu26,interval:auto,query:(match_all:()),sort:!('@timestamp',desc))):

```
org.postgresql.util.PSQLException: ERROR: column vn.sex does not exist
  Position: 156
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2497)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2233)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:446)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:370)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:149)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:138)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:64)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:79)
	at org.apache.ibatis.executor.BatchExecutor.doQuery(BatchExecutor.java:92)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:324)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:136)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:147)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:140)
	at org.apache.ibatis.binding.MapperMethod.executeForMany(MapperMethod.java:147)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:80)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:57)
	at com.sun.proxy.$Proxy113.listByTaxon(Unknown Source)
	at life.catalogue.dao.CatCopy.copyUsage(CatCopy.java:74)
	at life.catalogue.assembly.TreeCopyHandler.accept(TreeCopyHandler.java:222)
	at life.catalogue.assembly.TreeCopyHandler.accept(TreeCopyHandler.java:30)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at life.catalogue.assembly.SectorSync.processTree(SectorSync.java:204)
	at life.catalogue.assembly.SectorSync.sync(SectorSync.java:98)
	at life.catalogue.assembly.SectorSync.doWork(SectorSync.java:42)
	at life.catalogue.assembly.SectorRunnable.run(SectorRunnable.java:89)
	at life.catalogue.assembly.SectorSync.run(SectorSync.java:29)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

```
org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: org.postgresql.util.PSQLException: ERROR: column vn.sex does not exist
  Position: 156
### The error may exist in life/catalogue/db/mapper/VernacularNameMapper.xml
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: SELECT       vn.id,     vn.taxon_id,     vn.dataset_key,     vn.verbatim_key,     vn.name,     vn.latin,     vn.language,     vn.country,     vn.area,     vn.sex,     vn.reference_id,     vn.created,     vn.created_by,     vn.modified,     vn.modified_by         FROM  vernacular_name_30807 vn      WHERE vn.taxon_id = ?     ORDER BY name
### Cause: org.postgresql.util.PSQLException: ERROR: column vn.sex does not exist
  Position: 156
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:149)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:140)
	at org.apache.ibatis.binding.MapperMethod.executeForMany(MapperMethod.java:147)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:80)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:57)
	at com.sun.proxy.$Proxy113.listByTaxon(Unknown Source)
	at life.catalogue.dao.CatCopy.copyUsage(CatCopy.java:74)
	at life.catalogue.assembly.TreeCopyHandler.accept(TreeCopyHandler.java:222)
	at life.catalogue.assembly.TreeCopyHandler.accept(TreeCopyHandler.java:30)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at life.catalogue.assembly.SectorSync.processTree(SectorSync.java:204)
	at life.catalogue.assembly.SectorSync.sync(SectorSync.java:98)
	at life.catalogue.assembly.SectorSync.doWork(SectorSync.java:42)
	at life.catalogue.assembly.SectorRunnable.run(SectorRunnable.java:89)
	at life.catalogue.assembly.SectorSync.run(SectorSync.java:29)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.postgresql.util.PSQLException: ERROR: column vn.sex does not exist
  Position: 156
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2497)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2233)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:446)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:370)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:149)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:138)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:64)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:79)
	at org.apache.ibatis.executor.BatchExecutor.doQuery(BatchExecutor.java:92)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:324)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:136)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:147)
	... 19 common frames omitted
```

**Comment by mdoering** [comment]
ah, we need to wipe the dev db. Let me add that column manually quick

**Comment by mdoering** [comment]
done, please try once more

**Comment by gdower** [comment]
It's syncing now :+1:
