### ISSUE TITLE
Sector sync fails for non-draft catalogues

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-backend#596]
I'm trying to make a[ small assembly of just ScaleNet for Ruud](https://github.com/Sp2000/ConversionTool/issues/21). I followed the same procedure as [here](https://github.com/Sp2000/colplus-repo/issues/95), except adding the root taxon as [Animalia kingdom](https://github.com/Sp2000/colplus-backend/files/3980879/ScaleNet.zip) instead of Fungi. 

When I tried to sync, the frontend sent:

```JSON
POST https://api.dev.catalogue.life/assembly/30814/sync
{
  "sectorKey": 40614,
  "key": 40614,
  "target": {
    "id": "7e7bea98-8a36-43bd-994c-2493f4943340",
    "name": "Hemiptera",
    "rank": "order"
  },
  "subject": {
    "id": "xC",
    "name": "Coccoidea",
    "rank": "superfamily"
  }
}
```

Here's the [error logs for the failed sync](https://logs.gbif.org/app/kibana#/discover?_g=(refreshInterval:(display:On,pause:!f,value:0),time:(from:now-4h,mode:quick,to:now))&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:AWyLa2lBHCKcR6PFXu26,key:environment,negate:!f,type:phrase,value:col-dev),query:(match:(environment:(query:col-dev,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:AWyLa2lBHCKcR6PFXu26,key:sector,negate:!f,type:phrase,value:'40614'),query:(match:(sector:(query:'40614',type:phrase))))),index:AWyLa2lBHCKcR6PFXu26,interval:auto,query:(match_all:()),sort:!('@timestamp',desc))) with probably this being most important:

```
Sector Sync 40614 failed: life.catalogue.db.mapper.TaxonMapper.create (batch index #2) failed. 1 prior sub executor(s) completed successfully, but will be rolled back. Cause: java.sql.BatchUpdateException: Batch entry 0 INSERT INTO name_usage_3
        (id,  
         
        dataset_key,
        sector_key,
        verbatim_key,
        parent_id,
        name_id,
        status,
        is_synonym,
        origin,
        according_to,
        reference_ids,
        remarks,
        created_by,
        modified_by
     ,
        according_to_date,
        extinct,
        temporal_range_start,
        temporal_range_end,
        lifezones,
        webpage
     , created, modified)
        VALUES ('1806dbae-fdf0-48e0-8423-c96132be891c',  
         
        3,
        40614,
        NULL,
        '7e7bea98-8a36-43bd-994c-2493f4943340',
        '1bcf3332-cbfa-4394-a11e-cf7d1a3c6999',
        'ACCEPTED'::TAXONOMICSTATUS,
        'FALSE',
        'SOURCE'::ORIGIN,
        NULL,
        '{}',
        NULL,
        102,
        102
     ,
        NULL,
        NULL,
        NULL,
        NULL,
        '{}',
        NULL
     , now(), now()) was aborted: ERROR: insert or update on table "name_usage_3" violates foreign key constraint "name_usage_3_parent_id_fk"
  Detail: Key (parent_id)=(7e7bea98-8a36-43bd-994c-2493f4943340) is not present in table "name_usage_3".  Call getNextException to see other errors in the batch.
```

```
org.apache.ibatis.executor.BatchExecutorException: life.catalogue.db.mapper.TaxonMapper.create (batch index #2) failed. 1 prior sub executor(s) completed successfully, but will be rolled back. Cause: java.sql.BatchUpdateException: Batch entry 0 INSERT INTO name_usage_3
        (id,  
         
        dataset_key,
        sector_key,
        verbatim_key,
        parent_id,
        name_id,
        status,
        is_synonym,
        origin,
        according_to,
        reference_ids,
        remarks,
        created_by,
        modified_by
     ,
        according_to_date,
        extinct,
        temporal_range_start,
        temporal_range_end,
        lifezones,
        webpage
     , created, modified)
        VALUES ('1806dbae-fdf0-48e0-8423-c96132be891c',  
         
        3,
        40614,
        NULL,
        '7e7bea98-8a36-43bd-994c-2493f4943340',
        '1bcf3332-cbfa-4394-a11e-cf7d1a3c6999',
        'ACCEPTED'::TAXONOMICSTATUS,
        'FALSE',
        'SOURCE'::ORIGIN,
        NULL,
        '{}',
        NULL,
        102,
        102
     ,
        NULL,
        NULL,
        NULL,
        NULL,
        '{}',
        NULL
     , now(), now()) was aborted: ERROR: insert or update on table "name_usage_3" violates foreign key constraint "name_usage_3_parent_id_fk"
  Detail: Key (parent_id)=(7e7bea98-8a36-43bd-994c-2493f4943340) is not present in table "name_usage_3".  Call getNextException to see other errors in the batch.
	at org.apache.ibatis.executor.BatchExecutor.doFlushStatements(BatchExecutor.java:148)
	at org.apache.ibatis.executor.BaseExecutor.flushStatements(BaseExecutor.java:129)
	at org.apache.ibatis.executor.BaseExecutor.flushStatements(BaseExecutor.java:122)
	at org.apache.ibatis.executor.BatchExecutor.doQuery(BatchExecutor.java:86)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:324)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:136)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:147)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:140)
	at org.apache.ibatis.binding.MapperMethod.executeForMany(MapperMethod.java:147)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:80)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:57)
	at com.sun.proxy.$Proxy161.listByTaxon(Unknown Source)
	at life.catalogue.dao.CatCopy.copyUsage(CatCopy.java:74)
	at life.catalogue.assembly.TreeCopyHandler.accept(TreeCopyHandler.java:222)
	at life.catalogue.assembly.TreeCopyHandler.accept(TreeCopyHandler.java:30)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at life.catalogue.assembly.SectorSync.processTree(SectorSync.java:204)
	at life.catalogue.assembly.SectorSync.sync(SectorSync.java:98)
	at life.catalogue.assembly.SectorSync.doWork(SectorSync.java:42)
	at life.catalogue.assembly.SectorRunnable.run(SectorRunnable.java:89)
	at life.catalogue.assembly.SectorSync.run(SectorSync.java:29)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.sql.BatchUpdateException: Batch entry 0 INSERT INTO name_usage_3
        (id,  
         
        dataset_key,
        sector_key,
        verbatim_key,
        parent_id,
        name_id,
        status,
        is_synonym,
        origin,
        according_to,
        reference_ids,
        remarks,
        created_by,
        modified_by
     ,
        according_to_date,
        extinct,
        temporal_range_start,
        temporal_range_end,
        lifezones,
        webpage
     , created, modified)
        VALUES ('1806dbae-fdf0-48e0-8423-c96132be891c',  
         
        3,
        40614,
        NULL,
        '7e7bea98-8a36-43bd-994c-2493f4943340',
        '1bcf3332-cbfa-4394-a11e-cf7d1a3c6999',
        'ACCEPTED'::TAXONOMICSTATUS,
        'FALSE',
        'SOURCE'::ORIGIN,
        NULL,
        '{}',
        NULL,
        102,
        102
     ,
        NULL,
        NULL,
        NULL,
        NULL,
        '{}',
        NULL
     , now(), now()) was aborted: ERROR: insert or update on table "name_usage_3" violates foreign key constraint "name_usage_3_parent_id_fk"
  Detail: Key (parent_id)=(7e7bea98-8a36-43bd-994c-2493f4943340) is not present in table "name_usage_3".  Call getNextException to see other errors in the batch.
	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:148)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2234)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:510)
	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:853)
	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1546)
	at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:128)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java)
	at org.apache.ibatis.executor.BatchExecutor.doFlushStatements(BatchExecutor.java:122)
	... 26 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: insert or update on table "name_usage_3" violates foreign key constraint "name_usage_3_parent_id_fk"
  Detail: Key (parent_id)=(7e7bea98-8a36-43bd-994c-2493f4943340) is not present in table "name_usage_3".
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2497)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2233)
	... 32 common frames omitted
```

Frontend version: 0a54277 December 16, 2019 8:20 AM
Backend version: 590ab9d December 18, 2019 4:43 AM

**Comment by mdoering** [comment]
Removed various hardcoded draft catalogue magix numbers:
https://github.com/Sp2000/colplus-backend/commit/566808fc642814ee4ab32ef19b5db96f1cb44d61

https://github.com/Sp2000/colplus-backend/commit/8c0073d5c3ce6b06181bdab3e9203128f5843e29

https://github.com/Sp2000/colplus-backend/commit/bdc6b7234e08c837cf303b09ea3ce0ca474cb666
