### ISSUE TITLE
Duplicate key value violates unique constraint "decision_dataset_key_subject_dataset_key_subject_id_key"

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-backend#602]
To test application of decisions between dataset versions, @yroskov applied decisions to the **2019-03-28** edition of Scarabs. We then updated the dataset to **2019-05-28** edition which failed to import because of a duplicate decision_dataset_key_subject_dataset_key_subject_id_key. I tried to import again and hit the same bug.

I think it is because I'm generating non-persistent IDs that increment, and if the order of the names changed between monthly versions that would mean that the name and non-persistent ID would no longer match, and perhaps that causes the backend to panic. Tomorrow I'll generate persistent hash IDs based on the names for the March and May editions to see if that fixes the issue.

Probably a duplicate decision ID shouldn't cause an import to fail though.

Here's the [stacktrace](https://logs.gbif.org/app/kibana#/context/AWyLa4mQHCKcR6PFXu4X/logs/AW9oTVjhHCKcR6PFUgeJ?_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!t,index:AWyLa4mQHCKcR6PFXu4X,key:environment,negate:!f,type:phrase,value:col-prod),query:(match:(environment:(query:col-prod,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!t,index:AWyLa4mQHCKcR6PFXu4X,key:level,negate:!t,type:phrase,value:DEBUG),query:(match:(level:(query:DEBUG,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!t,index:AWyLa4mQHCKcR6PFXu4X,key:level,negate:!t,type:phrase,value:INFO),query:(match:(level:(query:INFO,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!t,index:AWyLa4mQHCKcR6PFXu4X,key:dataset,negate:!f,type:phrase,value:'1027'),query:(match:(dataset:(query:'1027',type:phrase))))),predecessorCount:5,sort:!('@timestamp',desc),successorCount:5)&_g=(refreshInterval:(display:On,pause:!f,value:0),time:(from:now-7d,mode:quick,to:now))):

```
org.apache.ibatis.exceptions.PersistenceException: 
### Error updating database.  Cause: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "decision_dataset_key_subject_dataset_key_subject_id_key"
  Detail: Key (dataset_key, subject_dataset_key, subject_id)=(3, 1027, syn-2934) already exists.
### The error may exist in life/catalogue/db/mapper/DecisionMapper.xml
### The error may involve life.catalogue.db.mapper.DecisionMapper.update-Inline
### The error occurred while setting parameters
### SQL: UPDATE decision     SET (      dataset_key,     subject_dataset_key,     subject_id,     subject_name,     subject_authorship,     subject_rank,     subject_code,     subject_status,     subject_parent,     note,     modified,     modified_by,     mode,     name,     status,     extinct,     temporal_range_start,     temporal_range_end,     lifezones    ) = (      ?,     ?,     ?,     ?,     ?,     ?::RANK,     ?::NOMCODE,     ?::TAXONOMICSTATUS,     ?,     ?,     now(),     ?,     ?::EDITORIALDECISION_MODE,     ?::jsonb,     ?::TAXONOMICSTATUS,     ?,     ?,     ?,     ?    )     WHERE key = ?
### Cause: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "decision_dataset_key_subject_dataset_key_subject_id_key"
  Detail: Key (dataset_key, subject_dataset_key, subject_id)=(3, 1027, syn-2934) already exists.
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:199)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:67)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:57)
	at com.sun.proxy.$Proxy116.update(Unknown Source)
	at life.catalogue.dao.SubjectRematcher.matchDecision(SubjectRematcher.java:209)
	at life.catalogue.dao.SubjectRematcher.matchDatasetDecision(SubjectRematcher.java:261)
	at life.catalogue.dao.SubjectRematcher.matchDatasetSubjects(SubjectRematcher.java:140)
	at life.catalogue.importer.ImportJob.importDataset(ImportJob.java:227)
	at life.catalogue.importer.ImportJob.run(ImportJob.java:122)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "decision_dataset_key_subject_dataset_key_subject_id_key"
  Detail: Key (dataset_key, subject_dataset_key, subject_id)=(3, 1027, syn-2934) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2497)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2233)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:446)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:370)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:149)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:138)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:47)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:74)
	at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:50)
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:197)
	... 13 common frames omitted
```

Frontend version: 8dcd15b December 20, 2019 4:21 PM
Backend version: 64b1a3d December 26, 2019 2:46 AM

**Comment by gdower** [comment]
@yroskov, I deleted all decisions for dataset 1027 (Scarabs), created persistent IDs for the synonyms for both the 2019-03-28 and 2019-05-28 versions, and re-imported the 2019-03-28 version. So tomorrow morning, you should be able to re-apply the decisions. Then you could change the data access url on the metadata page to 'https://github.com/Sp2000/data-scarabs/archive/2019-05-28.zip' and re-import the 2019-05-28 to see if it fixes the bug.

**Comment by mdoering** [comment]
When duplicate decisions occur now only one should be matched properly and the others stay as broken decisions around. We do the same with sectors.
