### ISSUE TITLE
Imports failing on dev: NullPointerException

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-backend#622]
When uploading a dataset on dev, I'm getting a [NullPointerException](https://logs.gbif.org/app/kibana#/context/AWyLa2lBHCKcR6PFXu26/logs/AXAL2B2bHCKcR6PF2psw?_a=(columns:!(_source),filters:!())):

```
java.lang.NullPointerException: null
	at life.catalogue.importer.Normalizer.insertData(Normalizer.java:801)
	at life.catalogue.importer.Normalizer.call(Normalizer.java:78)
	at life.catalogue.importer.ImportJob.importDataset(ImportJob.java:204)
	at life.catalogue.importer.ImportJob.run(ImportJob.java:120)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Frontend version: eb58917 January 31, 2020 8:59 AM
Backend version: 5409fd4 January 3, 2020 3:40 PM

**Comment by gdower** [comment]
@mdoering, whatever the issue was seems to have been temporary, because it's working now. I'll reopen if I get it again.
