### ISSUE TITLE
Release catalogue is silently crashing

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-backend#631]
As @mdoering and I discussed on gitter, it looks like the release catalogue process is silently crashing [without generating logging output](https://logs.gbif.org/app/kibana#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-12h,mode:quick,to:now))&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:AWyLa4mQHCKcR6PFXu4X,key:logger_name,negate:!f,type:phrase,value:life.catalogue.release.CatalogueRelease),query:(match:(logger_name:(query:life.catalogue.release.CatalogueRelease,type:phrase))))),index:AWyLa4mQHCKcR6PFXu4X,interval:auto,query:(match_all:()),sort:!('@timestamp',desc))) after copying the species estimates.

Here's a partially released example:

https://data.catalogue.life/catalogue/2072/dataset/2072/names

```
GET http://api.catalogue.life/assembly/3/release

Release catalogue 3 to new dataset2072
Map IDs
Copy all Sector
Copied 3315 Sector
Copy all Reference
Copied 1138148 Reference
Copy all Name
Copied 4004373 Name
Copy all NameRelation
Copied 0 NameRelation
Copy all Taxon
Copied 2199834 Taxon
Copy all Synonym
Copied 1710027 Synonym
Copy all VernacularName
Copied 452121 VernacularName
Copy all Distribution
Copied 2061310 Distribution
Copy all SpeciesEstimate
Copied 1266 SpeciesEstimate
```

**Comment by mdoering** [comment]
Logging in case of errors or success now guaranteed:
https://github.com/Sp2000/colplus-backend/commit/980b984084a0b50be20ab8b7e77711794b1179c1

Cause of the crash still needs to be found out

**Comment by gdower** [comment]
@mdoering, we're close to releasing the February edition! But we hit the [release bug](https://logs.gbif.org/app/kibana#/context/AWyLa4mQHCKcR6PFXu4X/logs/AXBZ8CBXHCKcR6PF_p0I?_a=(columns:!(_source),filters:!())):

```
org.apache.ibatis.exceptions.PersistenceException: 
### Error updating database.  Cause: org.postgresql.util.PSQLException: ERROR: column "locked" of relation "dataset_archive" does not exist
  Position: 372
### The error may exist in life/catalogue/db/mapper/DatasetMapper.xml
### The error may involve life.catalogue.db.mapper.DatasetMapper.createArchive-Inline
### The error occurred while setting parameters
### SQL: INSERT INTO dataset_archive (key, catalogue_key,         type,       title,       gbif_key,       gbif_publisher_key,       description,       organisations,       contact,       authors_and_editors,       license,       version,       released,       citation,       geographic_scope,       website,       logo,       data_format,       data_access,       origin,       locked,       import_frequency,       code,       notes,       alias,       "group",       confidence,       completeness,       settings,       created_by,       modified_by      , created, modified)         SELECT key, ?,         type,       title,       gbif_key,       gbif_publisher_key,       description,       organisations,       contact,       authors_and_editors,       license,       version,       released,       citation,       geographic_scope,       website,       logo,       data_format,       data_access,       origin,       locked,       import_frequency,       code,       notes,       alias,       "group",       confidence,       completeness,       settings,       created_by,       modified_by      , created, modified         FROM dataset d         WHERE d.key = ?
### Cause: org.postgresql.util.PSQLException: ERROR: column "locked" of relation "dataset_archive" does not exist
  Position: 372
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:199)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:184)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:62)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:57)
	at com.sun.proxy.$Proxy97.createArchive(Unknown Source)
	at life.catalogue.release.CatalogueRelease.lambda$copyData$0(CatalogueRelease.java:205)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at life.catalogue.release.CatalogueRelease.copyData(CatalogueRelease.java:203)
	at life.catalogue.release.CatalogueRelease.run(CatalogueRelease.java:141)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.postgresql.util.PSQLException: ERROR: column "locked" of relation "dataset_archive" does not exist
  Position: 372
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2497)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2233)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:446)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:370)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:149)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:138)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:47)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:74)
	at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:50)
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:197)
	... 12 common frames omitted
```

Frontend version: 6bf208a February 17, 2020 9:11 AM
Backend version: 980b984 February 12, 2020 10:19 AM

**Comment by mdoering** [comment]
should be fixed now, missing columns added

**Comment by mdoering** [comment]
Testing new release of draft on prod now: https://api.catalogue.life/assembly/3/release
I have deleted all previous release attempts from prod
